### ISSUE TITLE
Any plans to expand this with SSR(question)

### ISSUE THREAD

**Issue by jasan-s** [taming-the-state-in-react/nextjs-redux-firebase-authentication#1]
Main reason someone would choose nextjs is because SSR. All the logic in this repo in Client-side thus initial load or refresh the user would always show unauthed. Right?

**Comment by rwieruch** [comment]
No plans of doing it because of lack of time :(

**Comment by ummahusla** [comment]
What was the point of setting up a Next.js version without SSR?
