### ISSUE TITLE
Context not found error

### ISSUE THREAD

**Issue by Ik-williams** [taming-the-state-in-react/nextjs-redux-firebase-authentication#6]
After following all the necessary steps to install and run the app. When trying to access the app on localhost:3000 it says context not found. The live app seems to be running purely on react-js and redux without nextjs.

**Comment by rwieruch** [comment]
Hello @Ik-williams Can you check whether this PR https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/pulls works for you by checking out the branch? If you confirm, then I can merge the Pull Request. Had no time to do this myself, sorry.

**Comment by Ik-williams** [comment]
Hello mate!! Thanks for the quick response.  I have checked the  pull
request from
https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/pulls
and
it woks fine. But there is one slight issue when saving the new user. The
user is saved as undefined in firebase. The issue is that the new sign up
details are inserted within users collection inside an object undefined and
when queried returns undefined as an object with user details. Im sure
there is an easy fix for this. Thanks alot tho !!

**Comment by rwieruch** [comment]
Anyway you are able to add the Fix to the PR? Then we could merge it and people would be happy to have a version without bugs.

**Comment by Ik-williams** [comment]
Done!! created the pull request as requested.

**Comment by rwieruch** [comment]
Thank you @Ik-williams 👍  But I hoped you would extends the PR of @leonardoballand Now we have two Pull Requests for this thing 😬 

https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/pull/7
https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/pull/4

@Ik-williams @leonardoballand how do we proceed? 🎉

**Comment by leonardoballand** [comment]
He needs to commit on my PR. Or you could delete mine and merge the new PR if it is based on mine. Did you already review it?

**Comment by Ik-williams** [comment]
rwieruch, bruh Just delete one of the PR. **@leonardoballand**  is correct.

**Comment by rwieruch** [comment]
Which one should I merge? :)

**Comment by ummahusla** [comment]
I can suggest #4 as it was more stable when I pulled it down.

**Comment by rwieruch** [comment]
Fixed in https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/pull/7
